name: home-gate

services:
  phoenixd:
    container_name: phoenixd
    image: acinq/phoenixd:latest
    ports:
      - "9740:9740"
    volumes:
      - "./phoenixd:/phoenix/.phoenix"
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - phoenixd
    volumes:
      - ./back-end:/app
      - /app/node_modules
      - /app/dist
    restart: unless-stopped
    env_file:
      - ./back-end/.env

  frontend:
    container_name: frontend
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - phoenixd
    volumes:
      - ./front-end:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:4000

